a = input('digite algo:')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços?', a.isspace())
print('É um numero?', a.isnumeric())
print('É alfapetico?', a.isalpha())
print('É alpha numerico?', a.isalnum())
print('É alpha numerico?', a.isalnum())
print('esta em maiusculas?', a.isupper())
print('esta em minusculas?', a.islower())
print('esta capitalizada?', a.istitle())